# verbose level 0=info, 1=verbose, 2=very verbose
verbose: 0
listen:

# // SSH WS
- target_host: 127.0.0.1
  target_port: 109
  listen_port: 77
# // SSH WS
- target_host: 127.0.0.1
  target_port: 109
  listen_port: 2080